import clsx from "clsx";

import { initTheme } from "@/utils/theme";

import "./globals.css";

import { Montserrat, Merriweather } from "next/font/google";

const merriweather = Merriweather({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="dark" lang="ko">
      <body className={clsx(montserrat.variable, merriweather.variable, "bg-white", "dark:bg-zinc-800 dark:text-gray-100")}>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function() {
              ${initTheme.toString()}
              initTheme();
            })()`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
