import clsx from "clsx";

import { initTheme } from "@/utils/theme";

import "./globals.css";

import { Space_Grotesk } from "next/font/google";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-spaceGrotesk",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="dark" lang="ko">
      <body className={clsx(spaceGrotesk.variable, "bg-white", "dark:bg-zinc-800 dark:text-gray-100")}>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function() {
              ${initTheme.toString()}
              initTheme();
            })()`,
          }}
        />
        <main className="w-full h-screen">{children}</main>
      </body>
    </html>
  );
}
